In [2]:
import numpy as nm
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
Data_set = pd.read_excel("./d.xlsx")

In [4]:
Data_set

Time (in seconds)  Vehicle’s speed (in m/s)  \
0                0.020000                  0.000000   
1                0.027000                  0.000000   
2                0.037000                  0.000000   
3                0.047000                  0.000000   
4                0.057000                  0.000000   
...                   ...                       ...   
244338        2443.600000                  0.000000   
244339        2443.700000                  0.000000   
244340        2443.700000                  0.000000   
244341        1221.824441                  4.208266   
244342         705.427881                  4.589320   

        Engine Load (% of max power)  Total Acceleration (m/s^2)   Engine RPM  \
0                           0.000000                    0.000000     0.000000   
1                           0.000000                    0.000000     0.000000   
2                           0.000000                    0.000000     0.000000   
3                           0.000000                    0.000000     0.000000   
4                           0.000000                    0.000000     0.000000   
...                              ...                         ...          ...   
244338                      0.000000                    0.000000     0.000000   
244339                      0.000000                    0.000000     0.000000   
244340                      0.000000                    0.000000     0.000000   
244341                      6.506821                    0.084486  1346.820666   
244342                      6.381330                    0.903199   671.321649   

           Pitch  Lateral Acceleration (m/s^2)  
0      -0.323710                      0.000000  
1      -0.333910                      0.000000  
2      -0.344200                      0.000000  
3      -0.354570                      0.000000  
4      -0.365020                      0.000000  
...          ...                           ...  
244338  0.000000                      0.000000  
244339  0.000000                      0.000000  
244340  0.000000                      0.000000  
244341  0.493134                     -0.001158  
244342  2.703698                      0.461782  

[244343 rows x 7 columns]

In [28]:
X = Data_set.iloc[:,0:-1]
y = Data_set.iloc[:,-1]
X_ = Data_set.iloc[:,0:-1].values
y_ = Data_set.iloc[:,-1].values

In [22]:
y

0         0.000000
1         0.000000
2         0.000000
3         0.000000
4         0.000000
            ...   
244338    0.000000
244339    0.000000
244340    0.000000
244341   -0.001158
244342    0.461782
Name: Lateral Acceleration (m/s^2), Length: 244343, dtype: float64

In [7]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor()
reg.fit(X,y)

DecisionTreeRegressor()

In [8]:
reg.predict([[0.147,0,0,0,0,-0.145]])

array([0.])

In [9]:
reg.predict([[1.397,0.0021,0.0019,0.97,01279.8,-2.33]])

array([-2.56e-06])

In [10]:
import graphviz
from sklearn import tree

In [11]:
W=X.columns.values

In [12]:
dot_data = tree.export_graphviz(reg, out_file=None, 
                                feature_names=W,  
                                class_names=X,
                                filled=True)

In [13]:
text_representation = tree.export_text(reg)
print(text_representation)

|--- feature_0 <= 46.17
|   |--- feature_0 <= 41.03
|   |   |--- feature_5 <= -4.71
|   |   |   |--- feature_5 <= -4.88
|   |   |   |   |--- feature_1 <= 3.66
|   |   |   |   |   |--- feature_5 <= -4.95
|   |   |   |   |   |   |--- feature_0 <= 25.72
|   |   |   |   |   |   |   |--- feature_4 <= 1371.65
|   |   |   |   |   |   |   |   |--- feature_4 <= 1370.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 25.06
|   |   |   |   |   |   |   |   |   |   |--- value: [-1.47]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  25.06
|   |   |   |   |   |   |   |   |   |   |--- value: [-1.48]
|   |   |   |   |   |   |   |   |--- feature_4 >  1370.50
|   |   |   |   |   |   |   |   |   |--- feature_5 <= -4.96
|   |   |   |   |   |   |   |   |   |   |--- value: [-1.44]
|   |   |   |   |   |   |   |   |   |--- feature_5 >  -4.96
|   |   |   |   |   |   |   |   |   |   |--- value: [-1.42]
|   |   |   |   |   |   |   |--- feature_4 >  1371.65
|   |   |   |   |   |   |   |   |--- feature_

In [14]:
with open("decistion_tree.log", "w") as fout:
    fout.write(text_representation)

In [15]:
# fig = plt.figure(figsize=(25,20))
# _ = tree.plot_tree(reg, 
#                    feature_names=W,  
#                    filled=True)

In [20]:
X_.shape

(244343, 6)

In [33]:
X_[:200]

array([[ 2.0000e-02,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        -3.2371e-01],
       [ 2.7000e-02,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        -3.3391e-01],
       [ 3.7000e-02,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        -3.4420e-01],
       ...,
       [ 1.9870e+00, -9.0965e-04,  6.3000e+00, -5.5885e-01,  1.2650e+03,
        -3.2775e+00],
       [ 1.9970e+00, -5.5293e-04,  6.3000e+00, -5.6025e-01,  1.2648e+03,
        -3.2922e+00],
       [ 2.0070e+00, -9.8100e-04,  6.3000e+00, -5.6160e-01,  1.2646e+03,
        -3.3068e+00]])

In [31]:
y_.shape

(244343,)

In [36]:
plt.scatter(X_[:,0],y_[:0,0],color='blue')

IndexError: too many indices for array